#!/usr/bin/env bash
# Copyright 2026 The Google AI Edge Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Native end-to-end check of the C++ ModelChain pipeline, before the wasm
# build: builds sam2_chain_main (in the litert-samples workspace), runs the
# host-plan unit tests, then runs the pipeline on 24 frames of the football
# sample with 3 objects (2 clicks, 1 click, 3 clicks incl. a negative, joining
# at frame 6) under several configurations, and verifies each run with
# verify_chain.py (preprocess / masks vs HF / composite).
#
#   tools/native_e2e.sh [384|512]
set -euo pipefail
S="${1:-384}"
HERE="$(cd "$(dirname "$0")" && pwd)"
PROJ="$(dirname "$HERE")"
# External inputs (override with env vars; defaults: the repo root and ./artifacts, ./.venv).
SAMPLES="${LITERT_SAMPLES:-$(cd "$PROJ/../../../.." && pwd)}"  # the litert-samples repo this sample lives in
ARTROOT="${ARTIFACTS:-$PROJ/artifacts}"            # weights + run outputs
ART="$ARTROOT/chain"
PY="${PYTHON:-$PROJ/.venv/bin/python}"
BAZEL=(bazel --quiet)
FLAGS=(--noenable_platform_specific_config --copt=-w)
(cd "$SAMPLES" && bazel test "${FLAGS[@]}" //models/sam2/sam2_hiera_tiny_video/web_demo/cc:host_plan_test --test_output=errors)
(cd "$SAMPLES" && bazel build "${FLAGS[@]}" //models/sam2/sam2_hiera_tiny_video/web_demo/cc:sam2_chain_main)
BIN="$SAMPLES/bazel-bin/models/sam2/sam2_hiera_tiny_video/web_demo/cc/sam2_chain_main"

mkdir -p "$ART"
cd "$ART"
CLIP=football_640x360_24.rgba
[ -f "$CLIP" ] || ffmpeg -loglevel error -y -i "$PROJ/app/public/assets/football_ai_studio.mp4" \
  -frames:v 24 -vf scale=640:360 -f rawvideo -pix_fmt rgba "$CLIP"
# The Metal accelerator is loaded from the working directory.
cp -f "$SAMPLES/bazel-bin/models/sam2/sam2_hiera_tiny_video/web_demo/cc/sam2_chain_main.runfiles/litert_prebuilts/macos_arm64/libLiteRtMetalAccelerator.dylib" .

PROMPTS='0@0:0.44,0.28,1;0.46,0.40,1|1@0:0.484,0.79,1|2@6:0.14,0.32,2;0.215,0.645,3;0.15,0.34,0|3@0:0.194,0.342,2;0.253,0.632,3|4@3:0.594,0.352,2;0.658,0.632,3|5@2:0.45,0.71,2;0.53,0.865,3'
TFLITE="sam2_chain_$S.tflite"
"$BIN" --weights="$ARTROOT/sam2_tiny_${S}_video.safetensors" --image_size=$S \
  --host_consts="$PROJ/app/public/models/sam2_host_consts.safetensors" \
  --sam2_tflite="$TFLITE" --build_only

status=0
run() {  # tag, min_iou, min_mean_iou, extra flags...
  local tag=$1 min=$2 mean=$3; shift 3
  rm -rf "$tag"; mkdir -p "$tag"
  "$BIN" --image_size=$S --host_consts="$PROJ/app/public/models/sam2_host_consts.safetensors" \
    --sam2_tflite="$TFLITE" --reuse_tflite --frames_rgba=$CLIP --width=640 --height=360 --frames=24 \
    --prompts="$PROMPTS" --dump_dir="$tag" --dump_rgb=0,6,23 "$@" 2>&1 | grep -E '^median|^error' || true
  (cd "$HERE" && "$PY" verify_chain.py --dump "$ART/$tag" --rgba "$ART/$CLIP" --png \
      --min_iou $min --min_mean_iou $mean --tag "$tag" 2>&1 | grep -E '^ +(ok|FAIL|info)|^VERIFY') || status=1
  rm -f "$tag"/pixels_f*.f32  # large; regenerated by the next run
}
run "cpu${S}_nmm7_overlay" 0.95 0.99 --nmm=7 --effect=overlay
run "cpu${S}_nmm2_cutout" 0.95 0.99 --nmm=2 --effect=cutout
run "metal${S}_fp32_nmm7_spotlight" 0.95 0.99 --nmm=7 --effect=spotlight --accelerator=gpu --gpu_precision=fp32
run "metal${S}_fp16_nmm2_overlay" 0.85 0.98 --nmm=2 --effect=overlay --accelerator=gpu --gpu_precision=fp16
exit $status
