#!/usr/bin/env python3
# Copyright 2026 The Google AI Edge Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Generates runtime_stubs.inc from litert/c/internal/litert_runtime_c_api.h:
one LITERT_STUB(field) line per LiteRtRuntimeCApiStruct entry, so every
entry the JS-backed runtime does not implement fails loudly (and by name)
instead of being a null function pointer.

  python gen_runtime_stubs.py <litert_runtime_c_api.h> <out.inc>
"""
import re
import sys


def fields(header):
    s = open(header).read()
    body = s[s.index('typedef struct LiteRtRuntimeCApiStruct'):s.index('} LiteRtRuntimeCApiStruct;')]
    body = re.sub(r'//[^\n]*', '', body)
    body = body[body.index('{') + 1:]
    out = []
    depth, cur = 0, ''
    for ch in body:  # split on top-level ';'
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if ch == ';' and depth == 0:
            decl = ' '.join(cur.split())
            m = re.match(r'^(.*?)\(\s*\*\s*(\w+)\s*\)\s*\((.*)\)$', decl)
            if m:
                out.append((m.group(1).strip(), m.group(2), '...' in m.group(3)))
            cur = ''
        else:
            cur += ch
    return out


def main():
    header, dst = sys.argv[1], sys.argv[2]
    fs = fields(header)
    with open(dst, 'w') as f:
        f.write('// Generated by gen_runtime_stubs.py. Do not edit.\n')
        for ret, name, variadic in fs:
            f.write(f'LITERT_STUB{"_VARIADIC" if variadic else ""}({name})\n')
    print(f'{len(fs)} runtime entries -> {dst}')


if __name__ == '__main__':
    main()
