#!/usr/bin/env bash
# Copyright 2026 The Google AI Edge Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

# Builds app/public/wasm/sam2_chain.{mjs,wasm} with emscripten.
#
# Uses the SAME LiteRT snapshot / absl / flatbuffers as the native Bazel build
# (the litert-samples workspace's external repos), so native and wasm compile
# identical Tensor API, ModelChain and SAM 2 graph sources.
#
#   wasm/build.sh            (needs third_party/emsdk and a prior native build)
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
PROJ="$(dirname "$HERE")"
SAMPLES="${LITERT_SAMPLES:-$(cd "$PROJ/../../../.." && pwd)}"  # the litert-samples repo this sample lives in
if [ ! -f "$PROJ/third_party/emsdk/emsdk_env.sh" ]; then
  echo "error: emsdk not found at third_party/emsdk (see README: Setup from a fresh clone)" >&2
  exit 1
fi
source "$PROJ/third_party/emsdk/emsdk_env.sh" >/dev/null 2>&1

EXT="$(cd "$SAMPLES" && bazel info output_base 2>/dev/null)/external"
LITERT="$EXT/litert_archive"
GEN="$HERE/build/gen"
mkdir -p "$GEN/tflite/schema/mutable" "$GEN/litert/build_common"
# Bazel generates this from build_config.h.in; nothing is configured for wasm.
printf '#ifndef LITERT_BUILD_COMMON_BUILD_CONFIG_H_\n#define LITERT_BUILD_COMMON_BUILD_CONFIG_H_\n#endif\n' \
  > "$GEN/litert/build_common/build_config.h"

# flatbuffers schema header generated by the native build (same flatc/version).
SCHEMA="$SAMPLES/bazel-bin/external/litert_archive/tflite/schema/mutable/schema_generated.h"
[ -f "$SCHEMA" ] || (cd "$SAMPLES" && bazel build --noenable_platform_specific_config \
  @litert_archive//tflite/schema/mutable:schema_fbs_srcs 2>/dev/null || true)
cp -f "$SCHEMA" "$GEN/tflite/schema/mutable/schema_generated.h"

python3 "$HERE/patch_tflite_conversion.py" \
  "$LITERT/tensor/backends/tflite/tflite_flatbuffer_conversion.cc" "$GEN/tflite_flatbuffer_conversion.cc"
python3 "$HERE/gen_runtime_stubs.py" \
  "$LITERT/litert/c/internal/litert_runtime_c_api.h" "$GEN/runtime_stubs.inc"

GEN_FLAG=()
command -v ninja >/dev/null 2>&1 && GEN_FLAG=(-G Ninja)
emcmake cmake -S "$HERE" -B "$HERE/build" "${GEN_FLAG[@]}" -DCMAKE_BUILD_TYPE=Release \
  -DLITERT_ROOT="$LITERT" -DSAMPLES_ROOT="$SAMPLES" -DABSL_ROOT="$EXT/com_google_absl" \
  -DFLATBUFFERS_ROOT="$EXT/flatbuffers" -DGEN_DIR="$GEN" >/dev/null
cmake --build "$HERE/build" --target sam2_chain -j 8

OUT="$PROJ/app/public/wasm"
mkdir -p "$OUT"
cp -f "$HERE/build/sam2_chain.mjs" "$HERE/build/sam2_chain.wasm" "$OUT/"
ls -la "$OUT"
