/*
 * Copyright 2025 The Google AI Edge Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.ai.edge.examples.plantnet

/** PlantNet-300K species names, indexed by class id 0..1080
    (torchvision ImageFolder order = sorted species-id strings). */
object PlantNetLabels {
    val NAMES: Array<String> = arrayOf(
        "Lactuca virosa L.",
        "Pelargonium capitatum (L.) L'Hér.",
        "Pelargonium graveolens L'Hér.",
        "Cirsium arvense (L.) Scop.",
        "Cirsium vulgare (Savi) Ten.",
        "Pelargonium odoratissimum (L.) L'Hér.",
        "Pelargonium peltatum (L.) L'Hér.",
        "Pelargonium quercifolium (L. f.) L'Hér.",
        "Pelargonium zonale (L.) L'Hér.",
        "Mercurialis annua L.",
        "Phyllanthus tenellus Roxb.",
        "Hypericum perforatum L.",
        "Egeria densa Planch.",
        "Ibicella lutea (Lindl.) Van Eselt.",
        "Tradescantia fluminensis Vell.",
        "Tradescantia zebrina Heynh. ex Bosse",
        "Lamium amplexicaule L.",
        "Lavandula dentata L.",
        "Striga asiatica (L.) Kuntze",
        "Melilotus albus Medik.",
        "Trifolium fragiferum L.",
        "Asystasia gangetica (L.) T. Anderson",
        "Nymphaea nouchali Burm. f.",
        "Dryopteris aemula (Aiton) Kuntze",
        "Dryopteris affinis (Lowe) Fraser-Jenk.",
        "Dryopteris filix-mas (L.) Schott",
        "Nephrolepis cordifolia (L.) C. Presl",
        "Nephrolepis exaltata (L.) Schott",
        "Osmunda regalis L.",
        "Achyranthes aspera L.",
        "Lithodora fruticosa (L.) Griseb.",
        "Humulus lupulus L.",
        "Vaccaria hispanica (Mill.) Rauschert",
        "Spergularia rubra (L.) J. Presl & C. Presl",
        "Moehringia trinervia (L.) Clairv.",
        "Calendula officinalis L.",
        "Calendula stellata Cav.",
        "Carthamus caeruleus L.",
        "Carthamus lanatus L.",
        "Cirsium monspessulanum (L.) Hill",
        "Helminthotheca echioides (L.) Holub",
        "Hyoseris radiata L.",
        "Lactuca muralis (L.) Gaertn.",
        "Lactuca saligna L.",
        "Lactuca tenerrima Pourr.",
        "Limbarda crithmoides (L.) Dumort.",
        "Sedum acre L.",
        "Sedum album L.",
        "Sedum amplexicaule DC.",
        "Sedum andegavense (DC.) Desv.",
        "Sedum brevifolium DC.",
        "Sedum caeruleum L.",
        "Sedum caespitosum (Cav.) DC.",
        "Sedum cepaea L.",
        "Sedum dasyphyllum L.",
        "Sedum forsterianum Sm.",
        "Sedum hirsutum All.",
        "Sedum litoreum Guss.",
        "Sedum multiceps Coss. & Durieu",
        "Sedum rubens L.",
        "Sedum sediforme (Jacq.) Pau",
        "Alliaria petiolata (M. Bieb.) Cavara & Grande",
        "Boscia angustifolia A. Rich.",
        "Fibigia clypeata (L.) Medik.",
        "Maerua angolensis DC.",
        "Acalypha virginica L.",
        "Mercurialis perennis L.",
        "Phyllanthus reticulatus Poir.",
        "Hypericum androsaemum L.",
        "Hypericum australe Ten.",
        "Hypericum canariense L.",
        "Hypericum empetrifolium Willd.",
        "Hypericum hircinum L.",
        "Hypericum hirsutum L.",
        "Hypericum humifusum L.",
        "Hypericum linariifolium Vahl",
        "Hypericum montanum L.",
        "Hypericum perfoliatum L.",
        "Hypericum tetrapterum Fr.",
        "Hypericum tomentosum L.",
        "Lamium bifidum Cirillo",
        "Lamium flexuosum Ten.",
        "Lamium garganicum L.",
        "Lamium hybridum Vill.",
        "Lamium purpureum L.",
        "Lavandula canariensis Mill.",
        "Lavandula minutolii Bolle",
        "Lavandula multifida L.",
        "Lavandula stoechas L.",
        "Acacia mellifera (Vahl) Benth.",
        "Acacia seyal Delile",
        "Acacia tortilis (Forssk.) Hayne",
        "Galega officinalis L.",
        "Lupinus cosentinii Guss.",
        "Lupinus micranthus Guss.",
        "Melilotus italicus (L.) Lam.",
        "Melilotus sulcatus Desf.",
        "Trifolium angustifolium L.",
        "Trifolium arvense L.",
        "Trifolium aureum Pollich",
        "Trifolium campestre Schreb.",
        "Trifolium cherleri L.",
        "Trifolium hirtum All.",
        "Trifolium hybridum L.",
        "Trifolium incarnatum L.",
        "Trifolium lappaceum L.",
        "Trifolium michelianum Savi",
        "Trifolium micranthum Viv.",
        "Trifolium montanum L.",
        "Trifolium ochroleucon Huds.",
        "Trifolium pannonicum Jacq.",
        "Trifolium patens Schreb.",
        "Trifolium pratense L.",
        "Trifolium purpureum Loisel.",
        "Trifolium resupinatum L.",
        "Trifolium scabrum L.",
        "Trifolium spumosum L.",
        "Trifolium squamosum L.",
        "Trifolium stellatum L.",
        "Trifolium striatum L.",
        "Trifolium subterraneum L.",
        "Trifolium tomentosum L.",
        "Punica granatum L.",
        "Alcea rosea L.",
        "Althaea cannabina L.",
        "Althaea officinalis L.",
        "Nymphaea alba L.",
        "Hunnemannia fumariifolia Sweet",
        "Papaver atlanticum (Ball) Coss.",
        "Papaver rupifragum Boiss. & Reut.",
        "Goniolimon tataricum (L.) Boiss.",
        "Adonis aestivalis L.",
        "Adonis annua L.",
        "Adonis flammea Jacq.",
        "Adonis microcarpa DC.",
        "Anemone coronaria L.",
        "Anemone palmata L.",
        "Oldenlandia corymbosa L.",
        "Hyoscyamus albus L.",
        "Hyoscyamus niger L.",
        "Daphne gnidium L.",
        "Daphne laureola L.",
        "Daphne oleoides Schreb.",
        "Berula erecta (Huds.) Coville",
        "Chaerophyllum temulum L.",
        "Daucus muricatus (L.) L.",
        "Meum athamanticum Jacq.",
        "Thapsia garganica L.",
        "Thapsia villosa L.",
        "Centranthus calcitrapae (L.) Dufr.",
        "Fedia cornucopiae (L.) Gaertn.",
        "Pancratium canariense Ker Gawl.",
        "Pancratium maritimum L.",
        "Anthericum liliago L.",
        "Butomus umbellatus L.",
        "Danthonia decumbens (L.) DC.",
        "Leersia oryzoides (L.) Sw.",
        "Phalaris coerulescens Desf.",
        "Oncostema elongata (Parl.) Speta",
        "Oncostema peruviana (L.) Speta",
        "Elodea canadensis Michx.",
        "Neotinea maculata (Desf.) Stearn",
        "Ophrys apifera Huds.",
        "Ophrys bombyliflora Link",
        "Ophrys fusca Link",
        "Ophrys lutea Cav.",
        "Ophrys scolopax Cav.",
        "Ophrys speculum Link",
        "Ophrys tenthredinifera Willd.",
        "Groenlandia densa (L.) Fourr.",
        "Myosoton aquaticum (L.) Moench",
        "Cirsium palustre (L.) Scop.",
        "Lamium galeobdolon (L.) L.",
        "Lavandula angustifolia Mill.",
        "Casuarina cunninghamiana Miq.",
        "Trifolium rubens L.",
        "Falcaria vulgaris Bernh.",
        "Hypericum triquetrifolium Turra",
        "Wigandia caracasana Kunth",
        "Nymphaea lotus L.",
        "Sedum villosum L.",
        "Epipactis helleborine (L.) Crantz",
        "Thesium humifusum DC.",
        "Acacia etbaica Schweinf.",
        "Centranthus angustifolius (Mill.) DC.",
        "Centranthus lecoqii Jord.",
        "Sedum anglicum Huds.",
        "Sedum rupestre L.",
        "Ophrys insectifera L.",
        "Freesia refracta (Jacq.) Klatt",
        "Diatelia tuberaria (L.) Demoly",
        "Tradescantia pallida (Rose) D.R. Hunt",
        "Cenchrus longispinus (Hack.) Fernald",
        "Schefflera actinophylla (Endl.) Harms",
        "Cenchrus clandestinus (Hochst. ex Chiov.) Morrone",
        "Cenchrus purpureus (Schumach.) Morrone",
        "Cenchrus setaceus (Forssk.) Morrone",
        "Anemone hortensis L.",
        "Tradescantia cerinthoides Kunth",
        "Papaver argemone L.",
        "Papaver hybridum L.",
        "Papaver rhoeas L.",
        "Papaver dubium L.",
        "Papaver somniferum L.",
        "Daucus carota L.",
        "Smilax aspera L.",
        "Aizoon canariense L.",
        "Zannichellia palustris L.",
        "Secale cereale L.",
        "Cenchrus ciliaris L.",
        "Cenchrus echinatus L.",
        "Phalaris aquatica L.",
        "Phalaris arundinacea L.",
        "Phalaris canariensis L.",
        "Phalaris minor Retz.",
        "Phalaris paradoxa L.",
        "Sedum hispanicum L.",
        "Crotalaria juncea L.",
        "Lupinus angustifolius L.",
        "Lupinus luteus L.",
        "Lupinus pilosus L.",
        "Lupinus albus L.",
        "Trifolium alexandrinum L.",
        "Trifolium dubium Sibth.",
        "Trifolium glomeratum L.",
        "Trifolium nigrescens Viv.",
        "Trifolium repens L.",
        "Dalbergia melanoxylon Guill. & Perr.",
        "Melilotus indicus (L.) All.",
        "Melilotus officinalis (L.) Pall.",
        "Acacia dealbata Link",
        "Acacia longifolia (Andrews) Willd.",
        "Acacia mearnsii De Wild.",
        "Acacia pycnantha Benth.",
        "Acacia retinodes Schltdl.",
        "Barbarea verna (Mill.) Asch.",
        "Barbarea intermedia Boreau",
        "Myosurus minimus L.",
        "Fragaria vesca L.",
        "Duchesnea indica (Jacks.) Focke",
        "Centranthus ruber (L.) DC.",
        "Guizotia abyssinica (L. f.) Cass.",
        "Tagetes minuta L.",
        "Tagetes patula L.",
        "Calendula arvensis (Vaill.) L.",
        "Lapsana communis L.",
        "Carthamus tinctorius L.",
        "Lactuca sativa L.",
        "Lactuca serriola L.",
        "Arthraxon hispidus (Thunb.) Makino",
        "Microchloa kunthii Desv.",
        "Harpachne schimperi Hochst. ex A. Rich.",
        "Cedrela odorata L.",
        "Aeschynomene americana L.",
        "Prosopis alba Griseb.",
        "Prosopis juliflora (Sw.) DC.",
        "Crotalaria spectabilis Roth",
        "Crotalaria chrysochlora Baker f. ex Harms",
        "Crotalaria deflersii Schweinf.",
        "Crotalaria polysperma Kotschy",
        "Crotalaria uguenensis Taub.",
        "Crotalaria verrucosa L.",
        "Lupinus perennis L.",
        "Lupinus polyphyllus Lindl.",
        "Dalbergia latifolia Roxb.",
        "Cordyla africana Lour.",
        "Acacia xanthophloea Benth.",
        "Acacia drepanolobium Harms ex Y. Sjöstedt",
        "Acacia hockii De Wild.",
        "Acacia angustissima (Mill.) Kuntze",
        "Gomphocarpus integer (N.E. Br.) Bullock",
        "Trachelospermum jasminoides (Lindl.) Lem.",
        "Tradescantia spathacea Sw.",
        "Gymnosporia putterlickioides Loes.",
        "Conostomium kenyense Bremek.",
        "Conostomium quadrangulare (Rendle) Cufod.",
        "Mussaenda frondosa L.",
        "Mussaenda erythrophylla Schumach. & Thonn.",
        "Morinda citrifolia L.",
        "Pilocarpus racemosus Vahl",
        "Pelargonium alchemilloides (L.) L'Hér.",
        "Pelargonium quinquelobatum Hochst. ex A. Rich.",
        "Pelargonium glechomoides A. Rich.",
        "Gynura aurantiaca (Blume) DC.",
        "Gynura procumbens (Lour.) Merr.",
        "Tagetes erecta L.",
        "Aspilia mossambicensis (Oliv.) Wild",
        "Aspilia pluriseta Schweinf.",
        "Schkuhria pinnata (Lam.) Thell.",
        "Montanoa hibiscifolia Benth.",
        "Acalypha crenata Hochst. ex A. Rich.",
        "Acalypha hispida Burm. f.",
        "Phyllanthus fischeri Pax",
        "Phyllanthus suffrutescens Pax",
        "Phyllanthus acidus (L.) Skeels",
        "Phyllanthus amarus Schumach. & Thonn.",
        "Triadica sebifera (L.) Small",
        "Petiveria alliacea L.",
        "Peperomia pellucida (L.) Kunth",
        "Guaiacum officinale L.",
        "Hypericum annulatum Moris",
        "Mussaenda philippica A. Rich.",
        "Wigandia urens (Ruiz & Pav.) Kunth",
        "Boscia mossambicensis Klotzsch",
        "Boscia coriacea Pax",
        "Mecardonia procumbens (Mill.) Small",
        "Browallia americana L.",
        "Acacia mangium Willd.",
        "Casuarina equisetifolia L.",
        "Aristea abyssinica Pax",
        "Aristea ecklonii Baker",
        "Erianthemum dregei (Eckl. & Zeyh.) Tiegh.",
        "Cucurbita ficifolia Bouché",
        "Cucurbita pepo L.",
        "Luffa acutangula (L.) Roxb.",
        "Lagenaria siceraria (Molina) Standl.",
        "Lagenaria sphaerica (Sond.) Naudin",
        "Asystasia riparia Lindau",
        "Barringtonia asiatica (L.) Kurz",
        "Couroupita guianensis Aubl.",
        "Asystasia charmian S. Moore",
        "Raphia farinifera (Gaertn.) Hyl.",
        "Zamioculcas zamiifolia (Lodd.) Engl.",
        "Kniphofia linearifolia Baker",
        "Smilax anceps Willd.",
        "Vanilla planifolia Andrews",
        "Ansellia africana Lindl.",
        "Hypericum balearicum L.",
        "Ophrys druentica P.Delforge & Viglione",
        "Macrosyringion longiflorum (Vohl) Rothm.",
        "Pyracantha koidzumii (Hayata) Rehder",
        "Lactuca plumieri (L.) Gren. & Godr.",
        "Aizoanthemum hispanicum (L.) H.E.K.Hartmann",
        "Phedimus aizoon (L.) 't Hart",
        "Phedimus spurius (M.Bieb) 't Hart",
        "Nephrolepis cordifolia (L.) C.Presl",
        "Cereus jamacaru DC.",
        "Sedum pachyphyllum Rose",
        "Sedum dendroideum Moc. & Sessé ex DC.",
        "Liriodendron chinensis (Hemsl.) Sarg.",
        "Atocion rupestre (L.) B.Oxelman",
        "Tagetes tenuifolia Cav.",
        "Aegopodium podagraria L.",
        "Acacia melanoxylon R.Br.",
        "Acacia saligna (Labill.) H.L.Wendl.",
        "Patzkea paniculata (L.) G.H.Loos",
        "Perovskia abrotanoides Kar.",
        "Ophrys occidentalis (Scappaticci) Scappaticci & M.Demange",
        "Erechtites hieraciifolius (L.) Raf. ex DC.",
        "Cenchrus longisetus M.C.Johnst.",
        "Nothofagus obliqua (Mirb.) Oerst.",
        "Calendula arvensis L.",
        "Carthamus carduncellus L.",
        "Carthamus mitissimus L.",
        "Chaerophyllum aureum L.",
        "Chaerophyllum hirsutum L.",
        "Chaerophyllum villarsii W.D.J.Koch",
        "Cirsium alsophilum (Pollini) Greuter",
        "Cirsium canum (L.) All.",
        "Cirsium dissectum (L.) Hill",
        "Cirsium eriophorum (L.) Scop.",
        "Cirsium erisithales (Jacq.) Scop.",
        "Cirsium ferox (L.) DC.",
        "Cirsium filipendulum Lange",
        "Cirsium glabrum DC.",
        "Cirsium heterophyllum (L.) Hill",
        "Cirsium morisianum Rchb.f.",
        "Cirsium oleraceum (L.) Scop.",
        "Cirsium rivulare (Jacq.) All.",
        "Cirsium tuberosum (L.) All.",
        "Collomia grandiflora Douglas ex Lindl.",
        "Cucurbita maxima Duchesne",
        "Cymbalaria aequitriloba (Viv.) A.Chev.",
        "Cymbalaria hepaticifolia (Poir.) Wettst.",
        "Cytinus hypocistis (L.) L.",
        "Cytinus ruber Fritsch",
        "Daphne alpina L.",
        "Daphne cneorum L.",
        "Daphne mezereum L.",
        "Daphne striata Tratt.",
        "Dorotheanthus bellidiformis (Burm.f.) N.E.Br.",
        "Dryas octopetala L.",
        "Dryopteris carthusiana (Vill.) H.P.Fuchs",
        "Dryopteris cristata (L.) A.Gray",
        "Dryopteris dilatata (Hoffm.) A.Gray",
        "Dryopteris expansa (C.Presl) Fraser-Jenk. & Jermy",
        "Dryopteris villarii (Bellardi) Woyn. ex Schinz & Thell.",
        "Empetrum nigrum L.",
        "Epipactis atrorubens (Hoffm.) Besser",
        "Epipactis leptochila (Godfery) Godfery",
        "Epipactis microphylla (Ehrh.) Sw.",
        "Epipactis muelleri Godfery",
        "Epipactis palustris (L.) Crantz",
        "Epipactis phyllanthes G.E.Sm.",
        "Epipactis purpurata Sm.",
        "Erucastrum gallicum (Willd.) O.E.Schulz",
        "Erucastrum incanum (L.) W.D.J.Koch",
        "Erucastrum nasturtiifolium (Poir.) O.E.Schulz",
        "Fedia graciliflora Fisch. & C.A.Mey.",
        "Fragaria moschata Weston",
        "Freesia x hybrida L.H.Bailey",
        "Galega orientalis Lam.",
        "Alliaria petiolata (M.Bieb.) Cavara & Grande",
        "Geropogon hybridus (L.) Sch.Bip.",
        "Gomphocarpus fruticosus (L.) R.Br.",
        "Gomphocarpus physocarpus E.Mey.",
        "Guizotia abyssinica (L.f.) Cass.",
        "Hebe andersonii (Lindl. & Paxton) Cockayne",
        "Hebe brachysiphon Summerh.",
        "Hebe ochracea Ashwin",
        "Hebe salicifolia (G.Forst.) Pennell",
        "Helicodiceros muscivorus (L.f.) Engl.",
        "Hippophae rhamnoides L.",
        "Hypericum calycinum L.",
        "Hypericum coris L.",
        "Hypericum elodes L.",
        "Hypericum x inodorum Mill.",
        "Hypericum maculatum Crantz",
        "Hypericum nummularium L.",
        "Hypericum pulchrum L.",
        "Hypericum richeri Vill.",
        "Dierama pulcherrimum (Hook.f.) Baker",
        "Iva xanthiifolia Nutt.",
        "Kniphofia uvaria (L.) Hook.",
        "Lactuca alpina (L.) Benth. & Hook.f.",
        "Lactuca macrophylla (Willd.) A.Gray",
        "Lactuca viminea (L.) J.Presl & C.Presl",
        "Lamium album L.",
        "Lamium maculatum (L.) L.",
        "Lathraea clandestina L.",
        "Lathraea squamaria L.",
        "Lavandula x intermedia Emeric ex Loisel.",
        "Lavandula latifolia Medik.",
        "Limnanthes douglasii R.Br.",
        "Liriodendron tulipifera L.",
        "Lupinus arboreus Sims",
        "Lupinus x regalis Bergmans",
        "Maianthemum bifolium (L.) F.W.Schmidt",
        "Melilotus altissimus Thuill.",
        "Melilotus officinalis (L.) Lam.",
        "Melilotus spicatus (Sm.) Breistr.",
        "Mercurialis ambigua L.f.",
        "Mercurialis tomentosa L.",
        "Moehringia ciliata (Scop.) Dalla Torre",
        "Moehringia muscosa L.",
        "Moehringia pentandra J.Gay",
        "Narthecium ossifragum (L.) Huds.",
        "Neotinea lactea (Poir.) R.M.Bateman, Pridgeon & M.W.Chase",
        "Neotinea ustulata (L.) R.M.Bateman, Pridgeon & M.W.Chase",
        "Noccaea caerulescens (J.Presl & C.Presl) F.K.Mey.",
        "Noccaea montana (L.) F.K.Mey.",
        "Noccaea rotundifolia (L.) Moench",
        "Nymphaea candida C.Presl",
        "Nymphoides peltata (S.G.Gmel.) Kuntze",
        "Ophrys arachnitiformis Gren. & M.Philippe",
        "Ophrys aranifera Huds.",
        "Ophrys aveyronensis (J.J.Wood) P.Delforge",
        "Ophrys aymoninii (Breistr.) Buttler",
        "Ophrys bertolonii Moretti",
        "Ophrys catalaunica O.Danesch & E.Danesch",
        "Ophrys exaltata Ten.",
        "Ophrys fuciflora (F.W.Schmidt) Moench",
        "Ophrys incubacea Bianca",
        "Ophrys lupercalis Devillers & Devillers-Tersch.",
        "Ophrys morisii (Martelli) Soó",
        "Ophrys passionis Sennen",
        "Ophrys provincialis (Baumann & Künkele) Paulus",
        "Ophrys saratoi E.G.Camus",
        "Ophrys sulcata Devillers & Devillers-Tersch.",
        "Oreopteris limbosperma (Bellardi ex All.) Holub",
        "Anemone x hybrida Paxton",
        "Anemone alpina L.",
        "Pancratium illyricum L.",
        "Anemone apennina L.",
        "Anemone baldensis L.",
        "Papaver alpinum L.",
        "Papaver croceum Ledeb.",
        "Papaver orientale L.",
        "Papaver pseudoorientale (Fedde) Medw.",
        "Papaver rhaeticum Leresche",
        "Anemone halleri All.",
        "Anemone hepatica L.",
        "Pelargonium x hybridum (L.) Aiton",
        "Pelargonium inquinans (L.) Aiton",
        "Pelargonium peltatum (L.) Aiton",
        "Anemone montana Hoppe",
        "Anemone nemorosa L.",
        "Anemone pulsatilla L.",
        "Anemone rubra Lam.",
        "Phedimus stellatus (L.) Raf.",
        "Anemone sylvestris L.",
        "Anemone trifolia L.",
        "Anemone vernalis L.",
        "Angelica heterocarpa J.Lloyd",
        "Angelica razulii Gouan",
        "Angelica sylvestris L.",
        "Pleurospermum austriacum (L.) Hoffm.",
        "Sasa palmata (Burb.) Camus",
        "Anthericum ramosum L.",
        "Pyracantha coccinea M.Roem.",
        "Pyracantha rogersiana (A.B.Jacks.) Coltm.-Rog.",
        "Holodiscus discolor (Pursh) Maxim.",
        "Sagittaria graminea Michx.",
        "Sagittaria latifolia Willd.",
        "Sagittaria sagittifolia L.",
        "Diascia rigescens E.Mey. ex Benth.",
        "Diascia vigilis Hilliard & Burtt",
        "Sedum sarmentosum Bunge",
        "Sedum alpestre Vill.",
        "Sedum annuum L.",
        "Sedum kamtschaticum Fisch. & C.A.Mey.",
        "Sedum mexicanum Britton",
        "Sedum ochroleucum Chaix",
        "Sedum sexangulare L.",
        "Metasequoia glyptostroboides Hu & W.C.Cheng",
        "Telekia speciosa (Schreb.) Baumg.",
        "Thesium alpinum L.",
        "Thesium linophyllon L.",
        "Tradescantia x andersoniana F.Ludw. & Rohweder",
        "Tradescantia virginiana L.",
        "Trifolium alpestre L.",
        "Trifolium alpinum L.",
        "Trifolium pallescens Schreb.",
        "Trifolium spadiceum L.",
        "Trifolium thalii Vill.",
        "Viscaria alpina (L.) G.Don",
        "Viscaria vulgaris Bernh.",
        "Anemone hupehensis (Lemoine) Lemoine",
        "Anemone vitifolia Buch.-Ham. ex DC.",
        "Adenostyles alpina (L.) Bluff & Fingerh.",
        "Alcea biennis Winterl",
        "Anemone narcissiflora L.",
        "Anemone ranunculoides L.",
        "Angelica archangelica L.",
        "Chaerophyllum bulbosum L.",
        "Cirsium acaulon (L.) Scop.",
        "Cirsium spinosissimum (L.) Scop.",
        "Cymbalaria muralis P.Gaertn., B.Mey. & Scherb.",
        "Eritrichium nanum (L.) Schrad. ex Gaudin",
        "Fragaria viridis Weston",
        "Honckenya peploides (L.) Ehrh.",
        "Hypericum hyssopifolium Chaix",
        "Hypericum mutilum L.",
        "Lactuca perennis L.",
        "Sedum atratum L.",
        "Thesium pyrenaicum Pourr.",
        "Trifolium medium L.",
        "Trinia glauca (L.) Dumort.",
        "Sedum montanum Perrier & Songeon",
        "Trifolium badium Schreb.",
        "Freesia refracta (Jacq.) Eckl. ex Klatt",
        "Freesia alba (G.L.Mey.) Grumbleton",
        "Cobaea scandens Cav.",
        "Fragaria virginiana Duchesne",
        "Anemone pratensis L.",
        "Sagittaria lancifolia L.",
        "Neotinea tridentata (Scop.) R.M.Bateman, Pridgeon & M.W.Chase",
        "Adenostyles alliariae (Gouan) A.Kern.",
        "Ophrys pseudoscolopax (Moggr.) Paulus & Gack",
        "Sedum palmeri S.Watson",
        "Hypericum olympicum L.",
        "Tradescantia zebrina Bosse",
        "Dryopteris erythrosora (Eaton) Kuntze",
        "Adenostyles leucophylla (Willd.) Rchb.",
        "Calycanthus floridus L.",
        "Phyllanthus niruri L.",
        "Ophrys araneola sensu auct.plur.",
        "Anemone blanda Schott & Kotschy",
        "Aralia elata (Miq.) Seem.",
        "Ophrys virescens Philippe",
        "Clethra alnifolia L.",
        "Corispermum pallasii Steven",
        "Hypericum patulum Thunb.",
        "Hypericum x hidcoteense Hilling ex Geerinck",
        "Lupinus nootkatensis Donn ex Sims",
        "Smilax rotundifolia L.",
        "Perovskia atriplicifolia Benth.",
        "Nothofagus antarctica (G.Forst.) Oerst.",
        "Iva annua L.",
        "Dryopteris fragrans (L.) Schott",
        "Neotinea conica (Willd.) R.M.Bateman",
        "Tetraclinis articulata (Vahl) Mast.",
        "Alcea setosa (Boiss.) Alef.",
        "Chaerophyllum aromaticum L.",
        "Cucurbita moschata Duchesne",
        "Daphne sericea Vahl",
        "Lamium orvala L.",
        "Paederota bonarota (L.) L.",
        "Rhodothamnus chamaecistus (L.) Rchb.",
        "Ophrys lunulata Parl.",
        "Schefflera actinophylla Harms",
        "Astydamia latifolia Baill.",
        "Lavandula pinnata Moench",
        "Angelica atropurpurea L.",
        "Acacia pravissima F.Muell.",
        "Adonis pyrenaica DC.",
        "Adonis vernalis L.",
        "Barbarea rupicola Moris",
        "Barbarea vulgaris R.Br.",
        "Acacia baileyana F.Muell.",
        "Bellium bellidioides L.",
        "Bocoa prouacensis Aubl.",
        "Nephrolepis biserrata (Sw.) Schott",
        "Vanilla pompona Schiede",
        "Guatteria anteridifera Scharf & Maas",
        "Caraipa densifolia Mart.",
        "Caraipa punctulata Ducke",
        "Vismia cayennensis (Jacq.) Pers.",
        "Vismia macrophylla Kunth",
        "Vismia sessilifolia (Aubl.) Choisy",
        "Dryopteris wallichiana (Spreng.) Hyl.",
        "Xylopia frutescens Aubl.",
        "Xylopia nitida Dunal",
        "Xylopia sericea A.St.-Hil.",
        "Phyllanthus urinaria L.",
        "Pogonophora schomburgkiana Miers ex Benth.",
        "Sagotia racemosa Baill.",
        "Bonafousia undulata (Vahl) A.DC.",
        "Guarea gomma Pulle",
        "Nymphoides indica (L.) Kuntze",
        "Anthurium hookeri Kunth",
        "Anthurium jenmanii Engl.",
        "Anthurium scandens (Aubl.) Engl.",
        "Dracontium polyphyllum L.",
        "Crotalaria retusa L.",
        "Peperomia magnoliifolia (Jacq.) A.Dietr.",
        "Peperomia obtusifolia (L.) A.Dietr.",
        "Peperomia quadrangularis (J.V.Thomps.) A.Dietr.",
        "Peperomia rotundifolia (L.) Kunth",
        "Peperomia serpens (Sw.) Loudon",
        "Declieuxia fruticosa (Willd. ex Roem. & Schult.) Kuntze",
        "Mauritia flexuosa L.f.",
        "Urera baccifera (L.) Gaudich. ex Wedd.",
        "Pereskia bleo (Kunth) DC.",
        "Cereus hexagonus (L.) Mill.",
        "Xylopia crinita R.E.Fr.",
        "Vanilla planifolia Jacks.",
        "Aciotis rubricaulis (Mart. ex DC.) Triana",
        "Guatteria amplifolia Triana & Planch.",
        "Luffa cylindrica (L.) M.Roem.",
        "Cryptostegia madagascariensis Bojer ex Decne.",
        "Schefflera decaphylla (Seem.) Harms",
        "Aphelandra scabra (Vahl) Sm.",
        "Asystasia gangetica (L.) T.Anderson",
        "Piriqueta cistoides (L.) Griseb.",
        "Acalypha wilkesiana Müll.Arg.",
        "Breynia disticha J.R.Forst. & G.Forst.",
        "Crotalaria incana L.",
        "Crotalaria pallida Aiton",
        "Kigelia africana (Lam.) Benth.",
        "Guatteria citriodora Ducke",
        "Acalypha indica L.",
        "Guatteria punctata (Aubl.) R.A.Howard",
        "Anthurium crystallinum Linden & André",
        "Cryptopus elatus (Thouars) Lindl.",
        "Cryptostegia grandiflora R.Br.",
        "Eranthemum pulchellum Andrews",
        "Alocasia cucullata (Lour.) G.Don",
        "Alocasia longiloba Miq.",
        "Alocasia macrorrhizos (L.) G.Don",
        "Faujasia salicifolia (Pers.) C.Jeffrey",
        "Fernelia buxifolia Lam.",
        "Fragaria x ananassa Duchesne ex Rozier",
        "Geniostoma borbonicum (Lam.) Spreng.",
        "Hernandia mascarenensis (Meisn.) Kubitzki",
        "Hypericum lanceolatum Lam.",
        "Acacia auriculiformis A.Cunn. ex Benth.",
        "Leonitis nepetifolia (L.) R.Br.",
        "Mussaenda arcuata Poir.",
        "Nephrolepis abrupta (Bory) Mett.",
        "Acacia heterophylla (Lam.) Willd.",
        "Paederia foetida L.",
        "Pelargonium x asperum Ehrh. ex Willd.",
        "Pereskia grandifolia Haw.",
        "Antirhea borbonica J.F.Gmel.",
        "Phyllanthus emblica L.",
        "Phyllanthus niruroides Müll.Arg.",
        "Phyllanthus phillyreifolius Poir.",
        "Pongamia pinnata (L.) Pierre",
        "Acacia podalyriifolia A.Cunn. ex G.Don",
        "Schefflera actinophylla (F.Muell.) Harms",
        "Acalypha hispida Burm.f.",
        "Acalypha integrifolia Willd.",
        "Stemodia verticillata (Mill.) Hassl.",
        "Stoebe passerinoides (Lam.) Willd.",
        "Strongylodon macrobotrys A.Gray",
        "Tradescantia pallida (Rose) D.R.Hunt",
        "Trimezia martinicensis (Jacq.) Herb.",
        "Vangueria madagascariensis J.F.Gmel.",
        "Vepris lanceolata (Lam.) G.Don",
        "Zaleya pentandra (L.) C.Jeffrey",
        "Cereus repandus (L.) Mill.",
        "Bismarckia nobilis Hildebr. & H.Wendl.",
        "Acacia nilotica (L.) Delile",
        "Schefflera arboricola (Hayata) Merr.",
        "Fragaria chiloensis (L.) Mill.",
        "Aphelandra squarrosa Nees",
        "Gynura aurantiaca (Blume) Sch.Bip. ex DC.",
        "Pereskia aculeata Mill.",
        "Peperomia argyreia (Miq.) E.Morren",
        "Peperomia caperata Yunck.",
        "Peperomia obtusifolia (L.) A. Dietr.",
        "Anthurium andraeanum Linden ex André",
        "Anthurium scherzerianum Schott",
        "Zamia furfuracea L.f.",
        "Dendrobium nobile Lindl.",
        "Nandina domestica Thunb.",
        "Nymphaea nouchali Burm.f.",
        "Falcataria moluccana (Miq.) Barneby & J.W.Grimes",
        "Acacia tortuosa (L.) Willd.",
        "Bourreria succulenta Jacq.",
        "Crotalaria brevidens Benth.",
        "Crotalaria pumila Ortega",
        "Dendrobium chrysotoxum Lindl.",
        "Dendrobium crumenatum Sw.",
        "Dendrobium moschatum (Buch.-Ham.) Sw.",
        "Entada gigas (L.) Fawc. & Rendle",
        "Fittonia albivenis (Lindl. ex Veitch) R.K. Brummitt",
        "Illicium verum Hook.f.",
        "Lactuca floridana (L.) Gaertn.",
        "Mussaenda pubescens Dryand.",
        "Neolamarckia cadamba (Roxb.) Bosser",
        "Nymphaea ampla (Salisb.) DC.",
        "Phyllanthus epiphyllanthus L.",
        "Phyllanthus mimosoides Sw.",
        "Pilosocereus royeni (L.) Byles & G. Rowley",
        "Selenicereus anthonyanus (Alexander) D.Hunt",
        "Selenicereus grandiflorus (L.) Britton & Rose",
        "Zamia pumila L.",
        "Acalypha aristata Kunth",
        "Chamerion latifolium (L.) Holub",
        "Cirsium discolor (Muhl. ex Willd.) Spreng.",
        "Cirsium foliosum (Hook.) DC.",
        "Cirsium muticum Michx.",
        "Cirsium undulatum (Nutt.) Spreng.",
        "Comptonia peregrina (L.) J.M. Coult.",
        "Conoclinium coelestinum (L.) DC.",
        "Dalea purpurea Vent.",
        "Daucus pusillus Michx.",
        "Diervilla lonicera Mill.",
        "Dryopteris carthusiana (Vill.) H.P. Fuchs",
        "Dryopteris cristata (L.) A. Gray",
        "Dryopteris intermedia (Muhl. ex Willd.) A. Gray",
        "Dryopteris marginalis (L.) A. Gray",
        "Duchesnea indica (Andrews) Teschem.",
        "Epipactis gigantea Douglas ex Hook.",
        "Hypericum kalmianum L.",
        "Hypericum prolificum L.",
        "Hypericum punctatum Lam.",
        "Anemone canadensis L.",
        "Iva frutescens L.",
        "Anemone multifida Poir.",
        "Anemone virginiana L.",
        "Lactuca biennis (Moench) Fernald",
        "Lactuca canadensis L.",
        "Lamium maculatum L.",
        "Leersia virginica Willd.",
        "Angelica lucida L.",
        "Lupinus argenteus Pursh",
        "Lupinus bicolor Lindl.",
        "Maianthemum canadense Desf.",
        "Maianthemum racemosum (L.) Link",
        "Maianthemum stellatum (L.) Link",
        "Maianthemum trifolium (L.) Sloboda",
        "Mertensia maritima (L.) Gray",
        "Mertensia paniculata (Aiton) G. Don",
        "Mertensia virginica (L.) Pers. ex Link",
        "Mitella diphylla L.",
        "Moehringia lateriflora (L.) Fenzl",
        "Nymphaea mexicana Zucc.",
        "Nymphaea odorata Aiton",
        "Nymphaea tetragona Georgi",
        "Osmunda cinnamomea L.",
        "Osmunda claytoniana L.",
        "Papaver nudicaule L.",
        "Aralia hispida Vent.",
        "Aralia nudicaulis L.",
        "Aralia racemosa L.",
        "Pyracantha coccinea M. Roem.",
        "Sedum divergens S. Watson",
        "Sedum lanceolatum Torr.",
        "Sedum oreganum Nutt.",
        "Sedum spathulifolium Hook.",
        "Sedum ternatum Michx.",
        "Smilax herbacea L.",
        "Smilax tamnoides L.",
        "Tradescantia occidentalis (Britton) Smyth",
        "Tradescantia ohiensis Raf.",
        "Balsamorhiza sagittata (Pursh) Nutt.",
        "Barbarea orthoceras Ledeb.",
        "Barbarea vulgaris W.T. Aiton",
        "Calochortus macrocarpus Douglas",
        "Entada phaseoloides (L.) Merr.",
        "Cerbera manghas L.",
        "Hernandia cordigera Vieill.",
        "Acacia simplex (Sparman) Pedley",
        "Dubouzetia confusa Guillaumin & Virot",
        "Dubouzetia campanulata Pancher ex Brongn. & Gris",
        "Acacia spirorbis Labill.",
        "Atractocarpus platyxylon (Vieill. ex Pancher & Sebert) Guillaumin",
        "Nepenthes vieillardii Hook. f.",
        "Dendrobium closterium Rchb.f.",
        "Dracophyllum verticillatum Labill.",
        "Schefflera spp.",
        "Tagetes lucida Cav.",
        "Anisocampium niponicum (Mett.) Y.C.Liu, W.L. Chiou & M. Kato",
        "Mertensia ciliata (James ex Torr.) G. Don",
        "Lithops fulviceps N.E.Br.",
        "Lithops karasmontana N.E.Br.",
        "Lithops marmorata N.E.Br.",
        "Lithops pseudotruncatella N.E.Br.",
        "Fittonia albivenis (Lindl. ex Veitch) Brummitt",
        "Lithops spp.",
        "Cereus hildmannianus K.Schum.",
        "Neobuxbaumia polylopha (DC.) Backeb.",
        "Calycanthus occidentalis Hook. & Arn.",
        "Tradescantia subaspera Ker Gawl.",
        "Sedum kamtschaticum Fisch.",
        "Sedum lineare Thunb.",
        "Sedum morganianum E.Walther",
        "Cucurbita foetidissima Kunth",
        "Eucryphia cordifolia Cav.",
        "Dryopteris cycadina (Franch. & Sav.) C. Chr.",
        "Dryopteris erythrosora (D.C. Eaton) Kuntze",
        "Dryopteris sieboldii (T. Moore) Kuntze",
        "Rumohra adiantiformis (G. Forst.) Ching",
        "Oxydendrum arboreum (L.) DC.",
        "Lupinus albifrons Benth.",
        "Lycoris radiata (L'Hér.) Herb.",
        "Garrya elliptica Douglas ex Lindl.",
        "Lycoris squamigera Maxim.",
        "Pelargonium crispum (P.J. Bergius) L'Hér.",
        "Pelargonium x hortorum L.H. Bailey",
        "Loropetalum chinense (R. Br.) Oliv.",
        "Hypericum frondosum Michx.",
        "Liriope muscari (Decne.) L.H.Bailey",
        "Limnanthes douglasii R. Br.",
        "Nothofagus alpina (Poepp. & Endl.) Oerst.",
        "Nothofagus pumilio (Poepp. & Endl.) Krasser",
        "Abeliophyllum distichum Nakai",
        "Dendrobium aphyllum (Roxb.) C.E.C.Fisch.",
        "Dendrobium spp.",
        "Vanilla planifolia Jacks. ex Andrews",
        "Heteromorpha arborescens (Spreng.) Cham. & Schltdl.",
        "Lapageria rosea Ruiz & Pav.",
        "Peperomia argyreia (Hook.f.) E.Morren",
        "Peperomia dolabriformis Kunth",
        "Hebe franciscana (Eastw.) Souster",
        "Maurandya barclayana Lindl.",
        "Sasa palmata (Burb.) E.G.Camus",
        "Anemone patens L.",
        "Fragaria virginiana Mill.",
        "Fragaria x ananassa (Duchesne ex Weston) Duchesne ex Rozier",
        "Mussaenda philippica A.Rich.",
        "Limonia acidissima Groff",
        "Illicium floridanum J. Ellis",
        "Browallia speciosa Hook.",
        "Alocasia cuprea K.Koch",
        "Alocasia micholitziana Sander",
        "Alocasia odora (Lindl.) K.Koch",
        "Daphne odora Thunb.",
        "Alocasia sanderiana W.Bull",
        "Daphne tangutica Maxim.",
        "Kniphofia uvaria (L.) Oken",
        "Zamia furfuracea L.f. ex Aiton",
        "Guaiacum sanctum L.",
        "Nepenthes spp.",
        "Pelargonium spp.",
        "Pancratium maritimum L. L.",
        "Sedum palmeri S. Watson",
        "Aphelandra sinclairiana Nees",
        "Alocasia macrorrhizos (L.) G. Don",
        "Acacia confusa Merr.",
        "Acacia koaia Hillebr.",
        "Nephrolepis falcata (Cav.) C. Chr.",
        "Tradescantia zebrina hort. ex Bosse",
        "Calodendrum capense (L.f.) Thunb.",
        "Pelargonium grandiflorum Willd.",
        "Hypericum revolutum Vahl",
        "Schkuhria pinnata (Lam.) Kuntze ex Thell.",
        "Maytenus boaria Molina",
        "Melampodium perfoliatum (Cav.) Kunth",
        "Hernandia nymphaeifolia (J.Presl) Kubitzki",
        "Mazus pumilus (Burm.f.) Steenis",
        "Melampodium divaricatum (Rich.) DC.",
        "Breynia vitis-idaea (Burm.f.) C.E.C.Fisch.",
        "Prosopis farcta (Banks & Sol.) J.F.Macbr.",
        "Acacia farnesiana Willd.",
        "Freycinetia cumingiana Gaudich.",
        "Crotalaria laburnifolia L.",
        "Dalbergia sissoo DC.",
        "Dischidia nummularia R.Br.",
        "Schefflera heptaphylla (L.) Frodin",
        "Schinopsis balansae Engl.",
        "Smilax china L.",
        "Barringtonia acutangula (L.) Gaertn.",
        "Maerua triphylla A. Rich.",
        "Asystasia mysorensis (Roth) T.Anderson",
        "Lactuca virosa Habl.",
        "Calendula arvensis M.Bieb.",
        "Herbertia lahue (Molina) Goldblatt",
        "Hypericum hypericoides (L.) Crantz",
        "Hypericum tetrapetalum Lam.",
        "Keckiella cordifolia (Benth.) Straw",
        "Liriope muscari (Decne.) L.H. Bailey",
        "Lupinus chamissonis Eschsch.",
        "Lupinus diffusus Nutt.",
        "Lupinus formosus Greene",
        "Lupinus hirsutissimus Benth.",
        "Lupinus subcarnosus Hook.",
        "Lupinus texensis Hook.",
        "Lyonothamnus floribundus A. Gray",
        "Mazus pumilus (Burm. f.) Steenis",
        "Melampodium leucanthum Torr. & A. Gray",
        "Metasequoia glyptostroboides Hu & W.C. Cheng",
        "Aralia californica S. Watson",
        "Nyctaginia capitata Choisy",
        "Aralia spinosa L.",
        "Pelargonium panduriforme Eckl. & Zeyh.",
        "Pelargonium zonale (L.) L'Hér. ex Aiton",
        "Prosopis glandulosa Torr.",
        "Prosopis pubescens Benth.",
        "Sagittaria montevidensis Cham. & Schltdl.",
        "Sedum albomarginatum R.T. Clausen",
        "Sedum glaucophyllum R.T. Clausen",
        "Sedum laxum (Britton) A. Berger",
        "Sedum moranense Kunth",
        "Sedum niveum Davidson",
        "Sedum obtusatum A. Gray",
        "Sedum pulchellum Michx.",
        "Smilax bona-nox L.",
        "Smilax glauca Walter",
        "Smilax laurifolia L.",
        "Stanleya pinnata (Pursh) Britton",
        "Tagetes lemmonii A. Gray",
        "Tradescantia crassifolia Cav.",
        "Xylococcus bicolor Nutt.",
        "Brodiaea elegans Hoover",
        "Calochortus eurycarpus S. Watson",
        "Calochortus gunnisonii S. Watson",
        "Calochortus leichtlinii Hook. f.",
        "Calochortus luteus Douglas ex Lindl.",
        "Calochortus splendens Douglas ex Benth.",
        "Calochortus tolmiei Hook. & Arn.",
        "Calylophus hartwegii (Benth.) P.H. Raven",
        "Chaerophyllum tainturieri Hook.",
        "Cirsium altissimum (L.) Hill",
        "Cirsium horridulum Michx.",
        "Cirsium texanum Buckley",
        "Diervilla sessilifolia Buckley",
        "Acacia berlandieri Benth.",
        "Elephantopus elatus Bertol.",
        "Alocasia cucullata (Lour.) G. Don",
        "Acacia redolens Maslin",
        "Acacia rigidula Benth.",
        "Hackelia velutina (Piper) I.M. Johnst.",
        "Haplophyton crooksii (L.D. Benson) L.D. Benson",
        "Aextoxicon punctatum Ruiz & Pav.",
        "Lithops aucampiae L. Bolus",
        "Lithops olivacea L. Bolus",
        "Cyrtanthus elatus (Jacq.) Traub",
        "Guatteria aeruginosa Standl.",
        "Dischidia ovata Benth.",
        "Trachelospermum asiaticum (Siebold & Zucc.) Nakai",
        "Alocasia baginda Kurniawan & P.C.Boyce",
        "Alocasia lauterbachiana (Engl.) A.Hay",
        "Alocasia reginula A.Hay",
        "Alocasia wentii Engl. & K.Krause",
        "Alocasia zebrina Schott ex Van Houtte",
        "Anthurium clarinervium Matuda",
        "Anthurium faustomirandae Pérez-Farr. & Croat",
        "Anthurium salvinii Hemsl.",
        "Anthurium schlechtendalii Kunth",
        "Anthurium veitchii Mast.",
        "Anthurium warocqueanum T.Moore",
        "Wodyetia bifurcata A.K.Irvine",
        "Cereus forbesii C.F.Först.",
        "Cereus uruguayanus R. Kiesling",
        "Coryphantha elephantidens (Lem.) Lem.",
        "Pilosocereus chrysostele (Vaupel) Byles & G.D.Rowley",
        "Pilosocereus pachycladus F. Ritter",
        "Selenicereus anthonyanus (Alexander) D.R. Hunt",
        "Stenocactus multicostatus (Hildm.) A. Berger ex A.W. Hill",
        "Tephrocactus geometricus (A. Cast.) Backeb.",
        "Pterocephalus perennis Coult.",
        "Maytenus ilicifolia Mart. ex Reissek",
        "Cyanotis somaliensis C.B.Clarke",
        "Tradescantia × andersoniana W.Ludw. & Rohweder",
        "Tradescantia sillamontana Matuda",
        "Cirsium palustre (L.) Coss. ex Scop.",
        "Erechtites minima (Poir.) DC.",
        "Lactuca alpina (L.) A.Gray",
        "Leptinella potentillina F.Muell.",
        "Leucophyta brownii Cass.",
        "Melampodium divaricatum (Rich. ex Rich.) DC.",
        "Othonna capensis L.H.Bailey",
        "Rhodanthe chlorocephala (Turcz.) Paul G.Wilson",
        "Tagetes lemmonii A.Gray",
        "Tagetes lunulata Ortega",
        "Sedum adolphii Raym.-Hamet",
        "Sedum allantoides Rose",
        "Sedum burrito Moran",
        "Sedum clavatum R.T. Clausen",
        "Sedum compressum Rose",
        "Sedum cyaneum J. Rudolph",
        "Sedum decumbens R.T. Clausen",
        "Sedum furfuraceum Moran",
        "Sedum hernandezii J. Meyrán",
        "Sedum japonicum Siebold ex Miq.",
        "Sedum makinoi Maxim.",
        "Sedum nussbaumerianum Bitter",
        "Sedum praealtum A.DC.",
        "Sedum rubrotinctum R.T. Clausen",
        "Uncinia rubra Colenso ex Boott",
        "Empetrum rubrum Vahl ex Willd.",
        "Acalypha macrostachya Jacq.",
        "Pelargonium echinatum Curtis",
        "Pelargonium × hortorum L.H. Bailey",
        "Pelargonium sidoides DC.",
        "Pelargonium tomentosum Jacq.",
        "Lavandula canariensis (L.) Mill.",
        "Acacia auriculiformis Benth.",
        "Acacia brevispica Harms",
        "Acacia caven (Molina) Molina",
        "Acacia cognata Domin",
        "Acacia confluens Maiden & Blakeley",
        "Acacia podalyriifolia G.Don",
        "Acacia saligna (Labill.) Wendl.",
        "Dalbergia retusa Hemsl.",
        "Lupinus nootkatensis Sims",
        "Prosopis pallida (Willd.) Kunth",
        "Cedrela fissilis Vell.",
        "Nepenthes mirabilis (Lour.) Druce",
        "Nepenthes × neglecta Macfarl.",
        "Nothofagus betuloides (Mirb.) Oerst.",
        "Nothofagus dombeyi (Mirb.) Oerst.",
        "Nothofagus nitida (Phil.) Krasser",
        "Nymphaea rubra Roxb. ex Andrews",
        "Dendrobium anosmum Lindl.",
        "Dendrobium kingianum Bidwill ex Lindl.",
        "Dendrobium munificum (Finet) Schltr.",
        "Dendrobium thyrsiflorum B.S.Williams",
        "Dendrobium victoriae-reginae Loher",
        "Erycina pusilla (L.) N.H.Williams & M.W.Chase",
        "Adlumia fungosa (Aiton) Britton, Sterns & Poggenb.",
        "Peperomia albovittata C. DC.",
        "Peperomia clusiifolia (Jacq.) Hook.",
        "Peperomia columella Rauh & Hutchison",
        "Peperomia ferreyrae Yunck.",
        "Peperomia graveolens Rauh & Barthlott",
        "Peperomia maculosa (L.) Hook.",
        "Peperomia pecuniifolia Trel. & Standl.",
        "Peperomia polybotrya Kunth",
        "Peperomia prostrata B.S. Williams",
        "Peperomia tetragona Ruiz & Pav.",
        "Peperomia verticillata (L.) A.Dietr.",
        "Hebe andersonii (Lindl. & J. Paxton) Cockayne",
        "Lomatia ferruginea R. Br.",
        "Anemone pavoniana Boiss.",
        "Anemone tomentosa (Maxim.) C.Pei",
        "Hepatica nobilis Mill.",
        "Fragaria × ananassa (Duchesne ex Weston) Duchesne ex Rozier",
        "Margaritopsis haematocarpa (Standl.) C.M.Taylor",
        "Angostura granulosa (Kallunki) Kallunki",
        "Smilax excelsa L.",
        "Coussapoa villosa Poepp. & Endl.",
        "Cyphostemma cyphopetalum (Fresen.) Desc. ex Wild & R.B.Drumm.",
        "Cyphostemma juttae (Dinter & Gilg) Desc.",
        "Cyphostemma serpens (Hochst. ex A.Rich.) Desc.",
        "Nepenthes alata Blanco",
        "Nepenthes truncata Macfarl.",
        "Lavandula spp.",
        "Cymbalaria muralis P.Gaertn.",
        "Aphelandra aurantiaca Lindl.",
        "Guatteria dolichopoda Donn. Sm.",
        "Stenanona costaricensis R.E. Fr.",
        "Schefflera morototoni (Aubl.) Maguire",
        "Bourreria andrieuxii (DC.) Hemsl.",
        "Bourreria costaricensis (Standl.) A.H. Gentry",
        "Alibertia edulis (Rich.) A. Rich.",
        "Acacia senegalensis (Houtt.) Roberty"
    )
}
